name: everydaystuff
favicon: null
layout_spectrum: 1
typography_spectrum: 0.46662
title: Everydaystuff
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f06965'
    - '#ffcb5b'
    - '#3076bb'
    - '#ffffff'
    - '#97bfcb'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
