name: everydaystuff
favicon: null
layout_spectrum: 0.90616
typography_spectrum: 0.49008
title: Everydaystuff
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f06965'
    - '#ffcb5b'
    - '#3076bb'
    - '#ffffff'
    - '#97bfcb'
  brandStrength: 0.4375
  lightness: 0.9375
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
