name: everydaystuff
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5274046654812992
title: Everydaystuff
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffcc73'
    - '#231f38'
    - '#c4c5f3'
    - '#7577aa'
    - '#64d0ff'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
