name: everydaystuff
favicon: null
layout_spectrum: 0.8535558928269893
typography_spectrum: 0.5274046654812992
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.06798419076949358
  lightness: 0.7867288503330201
  saturation: 0.722838182002306
  rhythmicContrast: 0.7349084469024092
purpose: []
